[profile.default]
solc-version = "0.8.25"
libs = ['lib']
optimizer = true
optimizer_runs = 100_000
fuzz_max_global_rejects = 100_000

gas_reports = [
    ""
]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts",
]